# Generated by Django 6.1 on 2026-08-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pagemeta',
            new_name='seo_pagemet_url_pat_342117_idx',
            old_name='seo_pagemet_url_pat_4c8ddc_idx',
        ),
    ]
