# Generated by Django 5.2.17 on 2026-08-08 14:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('seo', '0002_rename_seo_pagemet_url_pat_4c8ddc_idx_seo_pagemet_url_pat_342117_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Бос')),
                ('mode', models.CharField(default='Соло/Паті', max_length=50)),
                ('diff', models.CharField(default='Середній/Високий', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Бос',
                'verbose_name_plural': 'Боси',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Назва глави')),
                ('slug', models.SlugField(help_text='gold-mask', unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Глави',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LootItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column_name', models.CharField(help_text='Лицар 68-65', max_length=100, verbose_name='Колонка')),
                ('item_name', models.CharField(max_length=200, verbose_name='Предмет')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='pagemeta',
            options={'verbose_name': 'SEO'},
        ),
        migrations.RemoveIndex(
            model_name='pagemeta',
            name='seo_pagemet_url_pat_342117_idx',
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='meta_description',
            field=models.TextField(max_length=160, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='meta_title',
            field=models.CharField(max_length=70, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='og_description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og/'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='og_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='robots_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='theme_color',
            field=models.CharField(default='#F1D07A', max_length=7, validators=[django.core.validators.RegexValidator(message='HEX #FFD700', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='url_path',
            field=models.CharField(blank=True, db_index=True, help_text='/', max_length=255, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='boss',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boss',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bosses', to='seo.chapter'),
        ),
        migrations.AddField(
            model_name='lootitem',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='seo.boss'),
        ),
        migrations.AddField(
            model_name='lootitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
